language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t eedys123/docker-fullstack -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true eedys123/docker-fullstack npm run test

after_success:
  - docker build -t eedys123/docker-frontend ./frontend
  - docker build -t eedys123/docker-backend ./backend
  - docker build -t eedys123/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push eedys123/docker-frontend 
  - docker push eedys123/docker-backend
  - docker push eedys123/docker-nginx


deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "fullstack"
  env: "Fullstack-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-638505169563
  bucket_path: "fullstack"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY